Dev
FreeCourseJava/vm_repo pull request #10
Opened 2022-07-10 13:05 UTC by shawtylo

2022-07-13 14:00 UTC, blekkiw requested changes

2022-07-13 14:00 UTC, blekkiw commented on src/lesson4/home/work/exercise_1/DrunkBrawlInTatarstan.java
> +        int arrayFirstElement = 0; int arrayLastElement = arrayForSorting.length;
Ммм. Никто не запрещает конечно писать в одну строчку, но лучше не надо.

2022-07-13 14:00 UTC, blekkiw commented on src/lesson4/home/work/exercise_1/DrunkBrawlInTatarstan.java
> +            if (!drinkShot)
{}

2022-07-13 14:00 UTC, blekkiw commented on src/lesson4/home/work/exercise_2/MethodForTatarstanWithRecursion.java
> +        if (resultOfSearching==randomYear){
Определись, ставишь пробелы между операторами или нет

2022-07-13 14:00 UTC, blekkiw commented on src/lesson4/home/work/exercise_2/MethodForTatarstanWithRecursion.java
> +        int randomYear = randomYears[getRandomArrayElementNumber(1,1,randomYears.length)];
Об эти два метода, getRandomArrayElementNumber и getSearchWithRecursion можно сломать мозг.
Во первых, тебе не нужны 1 и 1, они никогда не меняются. Лучше делать метод с меньшим количеством аргументов, и потом расширять. Плюс рандом можно сделать проще, но это ладно.
В getSearchWithRecursion вообще не нужны последние два аргумента, их можно спрятать внутрь метода

2022-07-17 10:55 UTC, shawtylo commented on src/lesson4/home/work/exercise_1/DrunkBrawlInTatarstan.java
> +        int arrayFirstElement = 0; int arrayLastElement = arrayForSorting.length;
поправил

2022-07-17 10:55 UTC, shawtylo commented on src/lesson4/home/work/exercise_1/DrunkBrawlInTatarstan.java
> +            if (!drinkShot)
добавил

2022-07-17 10:55 UTC, shawtylo commented on src/lesson4/home/work/exercise_2/MethodForTatarstanWithRecursion.java
> +        if (resultOfSearching==randomYear){
исправил. в старых заданиях тоже

2022-07-17 10:57 UTC, shawtylo commented on src/lesson4/home/work/exercise_2/MethodForTatarstanWithRecursion.java
> +        int randomYear = randomYears[getRandomArrayElementNumber(1,1,randomYears.length)];
getRandomArrayElementNumber и getSearchWithRecursion  - убрал лишние аргументы.

2022-07-17 10:57 UTC, merged