Задание к 7-му уроку
FreeCourseJava/vm_repo pull request #15
Opened 2022-08-07 11:07 UTC by shawtylo

2022-08-09 06:44 UTC, blekkiw requested changes

2022-08-09 06:44 UTC, blekkiw commented on src/lesson7/home/work/exercise1/Town.java
> +    public void getNewTownStreets (String streetName, int streetKadastrNumber, long streetLength, long streetWidth, boolean mainStreet, TownHouse[] townHouses, TownPark[] townParks) {
get - можно перевести как "дай". Но ты ничего не возвращаешь. Странное название

2022-08-09 06:44 UTC, blekkiw commented on src/lesson7/home/work/exercise1/Town.java
> +    public void getNewTownStreets (String streetName, int streetKadastrNumber, long streetLength, long streetWidth, boolean mainStreet, TownHouse[] townHouses, TownPark[] townParks) {
Мне кажется проще подать один объект типа TownStreet, чем 10 примитивов

2022-08-09 17:56 UTC, shawtylo commented on src/lesson7/home/work/exercise1/Town.java
> +    public void getNewTownStreets (String streetName, int streetKadastrNumber, long streetLength, long streetWidth, boolean mainStreet, TownHouse[] townHouses, TownPark[] townParks) {
поменял get на add

2022-08-10 07:43 UTC, blekkiw requested changes

2022-08-10 07:43 UTC, blekkiw commented on src/lesson7/home/work/exercise1/TownStreet.java
> +    String streetName;
Если ты все взаимодействия с полями закрыл, почему тогда тут не private?

2022-08-10 07:43 UTC, blekkiw commented on src/lesson7/home/work/exercise1/TownStreet.java
> +        this.townHouses = townHouses;
Опять же, если ты закрыл от изменений массивы, может и не стоит их в конструктор подавать?

2022-08-13 12:10 UTC, shawtylo commented on src/lesson7/home/work/exercise1/TownStreet.java
> +    String streetName;
поправил

2022-08-13 12:10 UTC, shawtylo commented on src/lesson7/home/work/exercise1/TownStreet.java
> +        this.townHouses = townHouses;
поправил, но не до конца уверен что правильно

2022-08-20 08:51 UTC, merged