Dev
FreeCourseJava/vm_repo pull request #5
Opened 2022-06-18 11:55 UTC by shawtylo

Задания второго урока
src/lesson_2_home_work/exercise_1/dateMillis.java
src/lesson_2_home_work/exercise_2/sumTwo.java
src/lesson_2_home_work/exercise_3/sumThree.java

2022-06-18 12:26 UTC, hyragano requested changes

2022-06-18 12:26 UTC, hyragano commented on src/lesson_1_home_work/lesson_1_git_exercises/exercise_1/sum.java
> +package lesson_1_home_work.lesson_1_git_exercises.exercise_1;
Пока пакеты не проходили, но если юзаешь. то там без _, разделяются слова точками. lesson.one.git.exercises

2022-06-18 12:26 UTC, hyragano commented on src/lesson_1_home_work/lesson_1_git_exercises/exercise_1/sum.java
> +        return bill + partOfBill;
если будет int overflow, то будет бяда и можно увести счет в овердрафт жёсткий. Хуяк и чел был миллионером, стал должен

2022-06-18 12:26 UTC, hyragano commented on src/lesson_1_home_work/lesson_1_theory_exercises/exercise_4.java
> +public class exercise_4 {
названия калссов CamelCase, но с заглавной. 
лучше пока просто какое-то одно слово юзать

2022-06-18 12:26 UTC, hyragano commented on src/lesson_2_home_work/exercise_1/dateMillis.java
> +    public static long getFirstDaysIntoMillis (int days){
круто конечно, но System.timeInMill лучше пока или как там его

2022-06-18 12:26 UTC, hyragano commented on src/lesson_2_home_work/exercise_3/sumThree.java
> +            if ( sum < 0 ) {
а если оба отрицательные? Тут нужно продумать проверку

2022-06-18 12:26 UTC, hyragano commented on src/lesson_2_home_work/exercise_3/sumThree.java
> +            if ( sum < 0 ) {
если нужен намек, то говори, а так играемся с edge cases

2022-06-19 09:42 UTC, shawtylo commented on src/lesson_1_home_work/lesson_1_git_exercises/exercise_1/sum.java
> +package lesson_1_home_work.lesson_1_git_exercises.exercise_1;
Пакеты переименовал. в новом коммите

2022-06-19 09:43 UTC, shawtylo commented on src/lesson_1_home_work/lesson_1_git_exercises/exercise_1/sum.java
> +        return bill + partOfBill;
Это задание из первого урока, там же про теор часть речь больше

2022-06-19 09:43 UTC, shawtylo commented on src/lesson_1_home_work/lesson_1_theory_exercises/exercise_4.java
> +public class exercise_4 {
Названия классов переименовал.  в новом коммите

2022-06-19 09:44 UTC, shawtylo commented on src/lesson_2_home_work/exercise_3/sumThree.java
> +            if ( sum < 0 ) {
Добавил еще блок if для проверки int underwlow.  в новом коммите

2022-06-20 15:08 UTC, hyragano requested changes
Так. Удалить не нужные коментарии. попытался поревьювить, но нойза очень много. Плз удали ненужные коментарии. И поправь один из моментов, которые я написал

2022-06-20 15:08 UTC, hyragano commented on src/lesson2/home/work/exercise_3/SumThree.java
> +    public static int getfinalScore (int bill, int partOfBill){
названиеМетодаДолжноБыть camelCase

2022-06-20 17:44 UTC, merged