Задания к 3-му уроку
FreeCourseJava/vm_repo pull request #8
Opened 2022-07-03 16:08 UTC by shawtylo

2022-07-03 19:13 UTC, hyragano requested changes

2022-07-03 19:13 UTC, hyragano commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +            List<Integer> listForExerciseArray = new ArrayList<>(valuesForChanges.length);
мы пока массивы проходим, с коллекциями и врапперами пока лучше не играться

2022-07-03 19:13 UTC, hyragano commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +            int randomElementFromValuesArray = new Random().ints(1, 0, valuesForChanges.length - 1).findFirst().getAsInt();
жуть, мб не стоит рандомы пока?

2022-07-03 19:13 UTC, hyragano commented on src/lesson3/home/work/exercise_3/MethodForTatarstan.java
> +    public static boolean getBinarySearch(int[] arrayForSearching, int valueForSearching) {
просто search  или exists, можно как-то так

2022-07-03 19:13 UTC, hyragano commented on src/lesson3/home/work/exercise_3/MethodForTatarstan.java
> +    public static int getRandomArrayElementNumber (int size, int minSize, int maxSize){
не стоит, тут еще есть проблема: у тебя 3 параметра с одним и тем же типом, это называется telescopic method. убираем пока что, но попытка норм

2022-07-03 19:20 UTC, hyragano requested changes

2022-07-03 19:20 UTC, hyragano commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +import java.util.stream.Stream;
ебиться сердце.... давай пока откатимся лучше,  no streams (не ожидал, что буду запрещать когда-либо стримы))))

2022-07-03 19:20 UTC, hyragano commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +//        int arraySizeForExercise = 4;
За коменты буду бить по рукам

2022-07-09 13:53 UTC, shawtylo commented on src/lesson3/home/work/exercise_3/MethodForTatarstan.java
> +    public static boolean getBinarySearch(int[] arrayForSearching, int valueForSearching) {
исправил

2022-07-09 13:54 UTC, shawtylo commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +import java.util.stream.Stream;
честно, пытался это просто через списки, но так и не победил. всё что со стримами в генераторе массива , больше заслуга ide

2022-07-09 13:55 UTC, shawtylo commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +//        int arraySizeForExercise = 4;
всё почистил

2022-07-09 14:03 UTC, shawtylo reviewed
@hyragano 
в общем, да, пока с экспериментами надо аккуратнее. но вроде победил. правда от стримов не избавился - сделал генератор массива через shuffle, и вот приведение списков в массивы и наоборот без стримов, как то не удалось придумать решение. 
но тут больше про то,что я пока о нем и не знаю)))

2022-07-09 14:05 UTC, shawtylo commented on src/lesson3/home/work/exercise_1/MinValueArray.java
> +        List<Integer> res = Arrays.asList(Arrays.stream(arrayForExercise).boxed().toArray(Integer[]::new));
уже заметил. сменил название на newArrayForExercise

2022-07-09 20:09 UTC, hyragano approved these changes

2022-07-10 10:11 UTC, merged